// Vhesap Merkezi Reklam & Tanıtım Veritabanı
// Bu dosya vhesap.html (Enterprise Yönetim Paneli) tarafından otomatik olarak üretilir.

window.GLOBAL_ADS = [
  {
    "id": "ad_1700000000001",
    "placement": "homeBottom",
    "type": "Banner",
    "title": "Vanaliz PRO - CFO Seviyesinde Analiz",
    "description": "Kredilerinizi çekmeden önce matematiksel analiz yapın, zarar etmekten kurtulun. Üstelik tamamen ücretsiz!",
    "buttonText": "Hemen İncele",
    "link": "vanaliz.html",
    "icon": "fa-solid fa-chart-pie",
    "badge": "ÖNE ÇIKAN",
    "transparentBg": false,
    "active": true,
    "priority": 10
  },
  {
    "id": "ad_1700000000002",
    "placement": "bireyselResult",
    "type": "Banner",
    "title": "Gizli Maliyetleri Anında Görün",
    "description": "İhtiyaç, Taşıt ve Konut kredisi hesaplamalarında KKDF ve BSMV gibi gizli maliyetleri şeffafça inceleyin.",
    "buttonText": "Kredi Hesapla",
    "link": "bireysel.html",
    "icon": "fa-solid fa-building-columns",
    "badge": "BİREYSEL",
    "transparentBg": false,
    "active": true,
    "priority": 9
  },
  {
    "id": "ad_1700000000003",
    "placement": "ticariResult",
    "type": "Banner",
    "title": "İşletmenizin Finansal Rotası",
    "description": "Rotatif, Spot ve İskonto kredi maliyetlerini kuruşu kuruşuna hesaplayın. Ticari risklerinizi minimize edin.",
    "buttonText": "Ticari Panele Git",
    "link": "ticari.html",
    "icon": "fa-solid fa-briefcase",
    "badge": "TİCARİ",
    "transparentBg": false,
    "active": true,
    "priority": 8
  },
  {
    "id": "ad_1700000000004",
    "placement": "vadeliResult",
    "type": "Banner",
    "title": "Net Getirinizi Önceden Bilin",
    "description": "Paranızı bağlamadan önce net getiriyi hesaplayın, vergi ve stopaj kesintilerini vade öncesinde netleştirin.",
    "buttonText": "Mevduat Hesapla",
    "link": "vadeli.html",
    "icon": "fa-solid fa-piggy-bank",
    "badge": "VADELİ",
    "transparentBg": false,
    "active": true,
    "priority": 7
  },
  {
    "id": "ad_1700000000005",
    "placement": "converterBottom",
    "type": "Banner",
    "title": "Anlık Çapraz Kur Çevirici",
    "description": "Döviz ve altın kurlarını anlık olarak çapraz çevirin, yatırımlarınızı hızlı ve hatasız planlayın.",
    "buttonText": "Çeviriciyi Aç",
    "link": "#",
    "icon": "fa-solid fa-arrow-right-arrow-left",
    "badge": "ARAÇLAR",
    "transparentBg": true,
    "active": true,
    "priority": 6
  },
  {
    "id": "ad_1700000000006",
    "placement": "planMid",
    "type": "Banner",
    "title": "Ödeme Planlarını PDF Olarak İndirin",
    "description": "Hesapladığınız karmaşık ödeme planlarını tek tıkla profesyonel PDF raporlarına dönüştürün.",
    "buttonText": "Nasıl Yapılır?",
    "link": "#",
    "icon": "fa-solid fa-file-pdf",
    "badge": "ÖZELLİK",
    "transparentBg": true,
    "active": true,
    "priority": 5
  },
  {
    "id": "ad_1700000000007",
    "placement": "blogTop",
    "type": "Banner",
    "title": "Esnek Ödeme Motorunu Keşfedin",
    "description": "Ara ödemeli, balon ödemeli veya azalan taksitli kendi esnek ödeme planlarınızı saniyeler içinde oluşturun.",
    "buttonText": "Hemen Dene",
    "link": "bireysel.html",
    "icon": "fa-solid fa-sliders",
    "badge": "PRO ÖZELLİK",
    "transparentBg": false,
    "active": true,
    "priority": 8
  },
  {
    "id": "ad_1700000000008",
    "placement": "blogMid",
    "type": "Banner",
    "title": "Ücretsiz Finans Okuryazarlığı Rehberi",
    "description": "Ekonomi, yatırım, vergi ve kredi dünyasındaki son gelişmeleri uzmanların kaleminden Vhesap Blog'da okuyun.",
    "buttonText": "Makalelere Göz At",
    "link": "blog.html",
    "icon": "fa-solid fa-book-open",
    "badge": "REHBER",
    "transparentBg": true,
    "active": true,
    "priority": 9
  },
  {
    "id": "ad_1700000000009",
    "placement": "blogBottom",
    "type": "Banner",
    "title": "Toplu Para Asistanı (Çığ & Kartopu)",
    "description": "Elinize geçen ekstra nakitle hangi borcunuzu kapatırsanız en çok kâra geçeceğinizi Vanaliz ile öğrenin.",
    "buttonText": "Vanaliz'e Git",
    "link": "vanaliz.html",
    "icon": "fa-solid fa-mountain",
    "badge": "ASİSTAN",
    "transparentBg": false,
    "active": true,
    "priority": 4
  },
  {
    "id": "ad_1700000000010",
    "placement": "blogCategoryEnd",
    "type": "Banner",
    "title": "Akıllı Kurtarma Asistanı",
    "description": "Finansal stres (T/G) oranınız yüksek mi? Algoritmamız size en uygun borç yapılandırma reçetesini sunsun.",
    "buttonText": "Stres Testi Yap",
    "link": "vanaliz.html",
    "icon": "fa-solid fa-shield-heart",
    "badge": "YENİ",
    "transparentBg": true,
    "active": true,
    "priority": 3
  },
  {
    "id": "ad_1700000000011",
    "placement": "vanalizAd",
    "type": "Banner",
    "title": "Vhesap: Kapsamlı Finans Portalı",
    "description": "Türkiye'nin en gelişmiş, ücretsiz finansal hesaplama ve simülasyon portalı. Hemen sık kullanılanlara ekleyin.",
    "buttonText": "Keşfet",
    "link": "index.html",
    "icon": "fa-solid fa-compass",
    "badge": "SİSTEM",
    "transparentBg": true,
    "active": true,
    "priority": 10
  }
];